In [3]:
pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/3f/6b/5610004206cf7f8e7ad91c5a85a8c71b2f2f8051a0c0c4d5916b76d6cbb2/numpy-1.26.4-cp311-cp311-win_amd64.whl.metadata
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.0 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.0 kB 330.3 kB/s eta 0:00:01
     ------------------------- ------------ 41.0/61.0 kB 281.8 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 362.9 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.1/15.8 MB 3.2 MB/s eta 0:00:05
   ---------------------------------------- 0.1/15.8 MB 787.7 kB/s eta 0:00:20
   ---------------------------------------- 0.2/15.8 MB 1.3 MB/s eta 0:00:12
    --------------------------------------- 0.2/15.8 MB 1.5 MB/s eta 0:00:11
   - -------------------------

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [8]:
# write your code here ^_^
x = np.ones(7)
print(x)

[1. 1. 1. 1. 1. 1. 1.]


## Q#2: Create y array with elements equal to 0.

In [10]:
# write your code here ^_^
y = np.full(7, 0)
print(y)

[0 0 0 0 0 0 0]


## Q#3: Add x and y arrays.

In [11]:
# write your code here ^_^
result = np.add(x, y)
print(result)

[1. 1. 1. 1. 1. 1. 1.]


## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [12]:
# write your code here ^_^
print("Dimension:", x.ndim)
print("Shape:", x.shape)
print("Size:", x.size)
print("Type:", x.dtype)

Dimension: 1
Shape: (7,)
Size: 7
Type: float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [16]:
# write your code here ^_^
w = np.array([[11, 12], [13, 14], [15, 16]])
print(w)

[[11 12]
 [13 14]
 [15 16]]


## Q#6: Create z array contains the numbers from 1 to 3.

In [17]:
# write your code here ^_^
z = np.arange(1, 4)
print(z)

[1 2 3]


## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [35]:
# write your code here ^_^
newArray = np.concatenate((z.reshape(-1, 1), w), axis=1)
print(newArray)

[[ 1 11 12]
 [ 2 13 14]
 [ 3 15 16]]


## Q#8: Print all elements of "newArray" using the loop.

In [28]:
# write your code here ^_^
for i in newArray:
    print(i)

[ 1 11 12]
[ 2 13 14]
[ 3 15 16]


## Q#9: Reverse the columns and rows of "newArray".

In [36]:
# write your code here ^_^
newArray = newArray[:, ::-1]
newArray = newArray[::-1, :]

print(newArray)

[[16 15  3]
 [14 13  2]
 [12 11  1]]


## Q#10: Decrement all elements of "newArray" with 1.

In [37]:
# write your code here ^_^
newArray -= 1

print(newArray)

[[15 14  2]
 [13 12  1]
 [11 10  0]]


## Q#11: Find smallest and biggest values in "newArray".

In [33]:
# write your code here ^_^
smallest = np.min(newArray)
biggest = np.max(newArray)

print("Smallest value:", smallest)
print("Biggest value:", biggest)

Smallest value: -1
Biggest value: 14


## Q#12: Print the first row of "newArray" using indexing.

In [43]:
# write your code here ^_^
print(np.take(newArray, [0], axis=0))

[[15 14  2]]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [47]:
# write your code here ^_^
print(newArray[newArray == 12])

[12]


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [46]:
# write your code here ^_^
print(newArray[newArray == 0])
print(newArray[newArray == 13])

[0]
[13]


## Q#15: Change the shape of "newArray" to (9,1).

In [48]:
# write your code here ^_^
newArray = np.reshape(newArray, (9, 1))

print(newArray)

[[15]
 [14]
 [ 2]
 [13]
 [12]
 [ 1]
 [11]
 [10]
 [ 0]]


## Q#16: Change the shape of "newArray" to (3,2).

In [51]:
# write your code here ^_^
newArray = newArray[:-3]
newArray = np.reshape(newArray, (3, 2))

print(newArray)

[[15 14]
 [ 2 13]
 [12  1]]


# Well Done 🎉